### ISSUE TITLE
Alphabetically sort attributes

### ISSUE THREAD

**Issue by devlato** [algolia/diffable-html#30]
Hey,

it would be great to sort the attributes alphabetically before formatting them. If that were implemented, diffs would be better, as the generated output would be more stable.

**Comment by rayrutjes** [comment]
That is a very interesting idea.

I'd love to have more voices on this before considering it.

I feel like it is definitely inline with what the library wants to achieve. 

It would impact all existing projects though and requiring proper communication so I want to make sure this is a feature most of us want.

**Comment by helloworld** [comment]
+1 Would love this.

We could simply add an `opts` argument to `toDiffableHtml` so that the library is backward compatible. 

```
toDiffableHtml(html, {
   sortAttributes: true,
})
```
The hard part is updating [jest-serializer-html](https://github.com/rayrutjes/jest-serializer-html) to be configurable. As far as I can tell, you can't pass any options or configuration to snapshot serializers.

**Comment by rayrutjes** [comment]
> The hard part is updating jest-serializer-html to be configurable

That is what I remember as well.
At the same time, this lib is called `diffable-html` and its intentions are clear, helping in providing meaningful and actionable HTML diffs. As a result, I'm inclined to make sorting the attributes the default and not require any configuration.

We just need to properly communicate about the change. All the projects will probably need to update the golden files which might not be ideal.

**Comment by helloworld** [comment]
> We just need to properly communicate about the change. All the projects will probably need to update the golden files which might not be ideal.

I don't currently have a large set of snapshots that use `jest-serializer-html`, but this definitely seems non-ideal for current users. Making attributes sorted by default would cause _massive_ diffs and breaking changes in existing snapshots that would be almost impossible to easily check for correctness. 

If you think making attributes sorted by default in `diffable-html` is correct, then I would recommend still adding an `options` argument where you can set `sortAttributes`. 

Then, in `jest-serializer-html`, you can pass in `sortAttributes: false` and make sure you dont thrash current `jest-serializer-html` users.

**Comment by rayrutjes** [comment]
@helloworld I'm very aligned with your vision. 

I think we need to add this as an opt-in if we move forward.

Regarding the Jest serializer, if there is no way to add options, I'd stick to the non-sorted attributes for now.

It's been a long time since I haven't used Jest. Isn't there a way to let users communicate with the Serializer somehow? For example by setting some kind of global variable that we could check to know whether to sort or not?

**Comment by helloworld** [comment]
Looks like we could use `setupFilesAfterEnv`: https://jestjs.io/docs/en/configuration.html#setupfilesafterenv-array

Here's the documentation for how to configure Enzyme: https://airbnb.io/enzyme/docs/guides/jest.html

**Comment by devlato** [comment]
> Making attributes sorted by default would cause massive diffs and breaking changes in existing snapshots that would be almost impossible to easily check for correctness.

@helloworld  Yeah, but it's gonna happen only once, and afterward, the produced snapshot will always remain stable (which hasn't been guaranteed so far).

I agree about adding a config option for enabling this, though – better to make devs decide whether they want a stable and predictable output, or they want to keep their existing snapshots.

**Comment by marcbachmann** [comment]
Can this be closed. https://github.com/algolia/diffable-html/pull/40 has landed a while back

**Comment by Haroenv** [comment]
Yes, an example of usage would be: 

```
import createSerializer from 'jest-serializer-html/createSerializer';

expect.addSnapshotSerializer(
  createSerializer({
    print: {
      sortAttributes: (names) => names.sort(),
    },
  })
);
```
